### ISSUE TITLE
Shortcut & gold

### ISSUE THREAD

**Issue by krijnsent** [k4zoo/Civ5ExpansionMod#24]
-The icon for gold (the resource to mine) changed and now shows up as a blank square.
-The shortcut for Pastures (P) doesn't work in your mod (it does in the normal game).

I do like playing the game with your mod better than the original, so hope you can fix this!
Thanks

**Comment by k4zoo** [comment]
fixed hopefully

**Comment by krijnsent** [comment]
Icon seems fixed, shortcut still broken in your mod, tested with 3.13.13
